# Generated by Django 4.2.3 on 2023-08-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_questionsubmission_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='choice',
        ),
    ]
