# Generated by Django 4.2.3 on 2023-07-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_userprofile_question_score_alter_quizscore_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
